### ISSUE TITLE
HTTP 500 when I access any page on a fresh installation

### ISSUE THREAD

**Issue by imxieyi** [vijos/vj4#404]
I installed from scratch in a docker container with Debian 8. `npm run build` finished without any error. However whatever page I access, an HTTP 500 error is raised. The log from console is as shown below:
```
[E 180301 05:27:06 web_protocol:310] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 310, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 741, in _iter
    resp = await method()
  File "/vj4/vj4/handler/domain.py", line 64, in get
    self.prepare_contest(), self.prepare_training(), self.prepare_discussion())
  File "/vj4/vj4/handler/domain.py", line 27, in prepare_contest
    if self.has_perm(builtin.PERM_VIEW_CONTEST):
  File "/vj4/vj4/handler/base.py", line 74, in has_perm
    role = self.domain_user.get('role', builtin.ROLE_DEFAULT)
AttributeError: 'DomainMainHandler' object has no attribute 'domain_user'
```
Upon further investigation I found that `HandlerBase.prepare()` in **base.py** is never called, which may be the reason for this issue. Is there any fix for this? Thanks ahead for any help.

**Comment by imxieyi** [comment]
I have found that the issue is from `aiohttp`. It works fine with `<=2.2.0`. With `3.0.x` it throws error as shown in the previous post.
With `2.3.x` it throws the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xieyi/vjj4/vj4/server.py", line 10, in <module>
    from aiohttp import web
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web.py", line 15, in <module>
    from . import (hdrs, web_exceptions, web_fileresponse, web_middlewares,
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_urldispatcher.py", line 20, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'
```

**Comment by twd2** [comment]
It seems aiohttp 3.0.x changes its interfaces again.  Will fix later.

**Comment by twd2** [comment]
Solved by #427
